//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubscriptionEditionsPrEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Follows
    {
        public int follow_id { get; set; }
        public int recipient_id { get; set; }
        public int publication_id { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<byte> period { get; set; }
    
        public virtual Publications Publications { get; set; }
        public virtual Recipients Recipients { get; set; }
    }
}
