//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubscriptionEditionsPrEP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EducPracEntities1 : DbContext
    {
        private static EducPracEntities1 _context;
        public EducPracEntities1()
            : base("name=EducPracEntities1")
        {
        }
        public static EducPracEntities1 GetContext()
        {
            if (_context == null)
                _context = new EducPracEntities1();

            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Follows> Follows { get; set; }
        public virtual DbSet<Publications> Publications { get; set; }
        public virtual DbSet<Recipients> Recipients { get; set; }
    }
}
